import { createContext, useContext, useState, useEffect, useCallback, useMemo, type ReactNode } from 'react';

export type Lang = 'zh-CN' | 'zh-TW' | 'en';

interface LanguageContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  toggleLang: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const STORAGE_KEY = 'gold_hedge_lang';

// 全量三语文案
const translations: Record<Lang, Record<string, string>> = {
  'zh-CN': {
    // 导航
    'nav.assistant': '智能问答',
    'nav.risk': '风险评估',
    'nav.calculator': '行业配置',
    'nav.backtest': '回测看板',
    'nav.research': '研究结论',
    'nav.reports': '研究报告',
    'nav.contact': '联系作者',
    'nav.lang': '语言',

    // 风险评估
    'risk.title': '投资者风险评估',
    'risk.subtitle': '填写问卷，获得个性化的风险偏好分析和对冲建议',
    'risk.question.1.title': '投资经验',
    'risk.question.1.desc': '您的投资经验有多久？',
    'risk.question.1.option.1': '1年以内',
    'risk.question.1.option.2': '1-3年',
    'risk.question.1.option.3': '3-5年',
    'risk.question.1.option.4': '5年以上',
    'risk.question.2.title': '风险承受能力',
    'risk.question.2.desc': '当您的投资亏损20%时，您会怎么做？',
    'risk.question.2.option.1': '立即全部止损',
    'risk.question.2.option.2': '部分止损，等待机会',
    'risk.question.2.option.3': '保持持有，等待反弹',
    'risk.question.2.option.4': '逆势加仓',
    'risk.question.3.title': '投资目标',
    'risk.question.3.desc': '您的主要投资目标是什么？',
    'risk.question.3.option.1': '保本为主，少量增值',
    'risk.question.3.option.2': '稳健增值，适度波动',
    'risk.question.3.option.3': '追求较高收益，接受波动',
    'risk.question.3.option.4': '最大化收益，愿承担高风险',
    'risk.question.4.title': '投资期限',
    'risk.question.4.desc': '您的投资期限是多久？',
    'risk.question.4.option.1': '1年以内',
    'risk.question.4.option.2': '1-3年',
    'risk.question.4.option.3': '3-5年',
    'risk.question.4.option.4': '5年以上',
    'risk.next': '下一题',
    'risk.prev': '上一题',
    'risk.submit': '查看结果',
    'risk.result.title': '您的风险评估结果',
    'risk.result.profile': '风险偏好类型',
    'risk.result.recommendation': '对冲配置建议',
    'risk.result.gold.ratio': '建议黄金配置比例',
    'risk.result.description': '详细说明',
    'risk.type.conservative': '保守型投资者',
    'risk.type.moderate': '稳健型投资者',
    'risk.type.balanced': '平衡型投资者',
    'risk.type.aggressive': '进取型投资者',
    'risk.type.veryAggressive': '激进型投资者',
    'risk.retake': '重新评估',
    'risk.goToCalculator': '使用计算器细化',

    // 首页 - 智能问答
    'home.hero.title': '黄金 · 股票跨资产自适应对冲策略',
    'home.hero.subtitle': '用智能问答，秒级获取您专属的黄金ETF配置方案',
    'home.placeholder': '例如：我重仓了科技股，应该配多少黄金对冲？',
    'home.submit': '生成建议',
    'home.examples.title': '试试这些问题',
    'home.examples.1': '我重仓了科技股，应该配多少黄金对冲？',
    'home.examples.2': '现在通胀高，能源股配多少黄金合适？',
    'home.examples.3': '保守型投资者，消费行业怎么配黄金ETF？',
    'home.result.title': '配置建议',
    'home.result.ratio': '建议黄金配置比例',
    'home.result.logic': '对冲逻辑说明',
    'home.result.risk': '风险提示',
    'home.result.loading': '正在为您分析...',
    'home.result.analyzing': '正在解析您的问题...',
    'home.result.generating': '正在生成配置建议...',
    'home.result.error': '解析失败，请尝试更明确的描述，或使用行业配置计算器手动调整。',
    'home.model.select': '选择AI模型',
    'home.ai.settings': 'AI设置',

    // 计算器
    'calc.title': '行业配置计算器',
    'calc.subtitle': '选择行业与市场参数，实时计算最优黄金对冲比例',
    'calc.industry': '选择行业',
    'calc.risk': '风险偏好',
    'calc.risk.conservative': '保守型',
    'calc.risk.moderate': '稳健型',
    'calc.risk.aggressive': '激进型',
    'calc.market': '市场状态调节',
    'calc.volatility': '市场波动',
    'calc.volatility.low': '低波动',
    'calc.volatility.normal': '正常',
    'calc.volatility.high': '高波动',
    'calc.inflation': '通胀水平',
    'calc.inflation.low': '低通胀',
    'calc.inflation.high': '高通胀',
    'calc.panic': '恐慌程度',
    'calc.panic.low': '低恐慌',
    'calc.panic.high': '高恐慌',
    'calc.result.title': '计算结果',
    'calc.result.ratio': '建议黄金ETF配置比例',
    'calc.result.effect': '预期对冲效果',
    'calc.result.protection': '下行保护强度',
    'calc.formula.title': '计算过程',
    'calc.formula.base': '基准比例',
    'calc.formula.industry': '行业系数',
    'calc.formula.market': '市场调整',
    'calc.formula.result': '最终比例',
    'calc.effect.strong': '强',
    'calc.effect.medium': '中',
    'calc.effect.weak': '弱',

    // 回测
    'backtest.title': '策略回测看板',
    'backtest.subtitle': '自适应策略 vs 静态对冲 vs 纯股票，历史表现一目了然',
    'backtest.kpi.annual': '年化收益',
    'backtest.kpi.drawdown': '最大回撤',
    'backtest.kpi.sharpe': '夏普比率',
    'backtest.kpi.protection': '下行保护率',
    'backtest.chart.curve': '累计收益对比',
    'backtest.chart.inflation': '通胀状态分布',
    'backtest.chart.vix': 'VIX状态分布',
    'backtest.strategy.adaptive': '自适应策略',
    'backtest.strategy.static': '静态对冲',
    'backtest.strategy.stock': '纯股票',
    'backtest.inflation.high': '高通胀',
    'backtest.inflation.low': '低通胀',
    'backtest.vix.high': '高VIX',
    'backtest.vix.low': '低VIX',

    // 研究结论
    'research.title': '核心研究发现',
    'research.subtitle': '基于十年跨资产数据的实证结论',
    'research.f1.title': '行业异质性',
    'research.f1.desc': '不同行业对黄金对冲的敏感度差异显著，能源、公用事业等周期防御型行业对冲效果最强，科技、地产等成长/利率敏感型行业相对较弱。',
    'research.f2.title': '状态依赖',
    'research.f2.desc': '黄金对冲效果高度依赖市场状态：高通胀、高恐慌、高波动环境下对冲效率显著提升，平稳市场中则表现为收益拖累。',
    'research.f3.title': '非对称对冲',
    'research.f3.desc': '黄金在股市下跌时的保护作用远强于上涨时的拖累效应，呈现典型的"危机Alpha"非对称特征，下行保护率显著高于上行损耗率。',
    'research.f4.title': '避险边界',
    'research.f4.desc': '黄金对冲并非万能：在美元流动性危机、实际利率快速上行等特殊场景下，黄金与股票可能同步下跌，需警惕避险资产的阶段性失效风险。',

    // 联系作者
    'contact.title': '联系作者',
    'contact.subtitle': '如有任何问题或合作意向，请联系我们',
    'contact.email': '邮箱',
    'contact.email.placeholder': '请输入您的邮箱',
    'contact.message': '消息',
    'contact.message.placeholder': '请输入您的消息',
    'contact.submit': '发送',
    'contact.success': '消息发送成功！',
    'contact.or.write': '或直接发送邮件至',
    'contact.info': '关于本项目',
    'contact.info.desc': '本项目旨在帮助投资者科学地进行黄金与股票的跨资产对冲配置，基于学术研究成果开发。',

    // 通用
    'common.percent': '%',
    'common.vs': '对比',
    'common.basisPoint': 'bp',
    // 市场看板
    'nav.market': '市场看板',
    'market.title': '实时市场数据看板',
    'market.subtitle': '实时追踪黄金、股票和外汇等资产的对冲表现',
    'market.updateMode': '更新模式',
    'market.polling': '轮询模式',
    'market.websocket': 'WebSocket 实时',
    'market.refreshInterval': '刷新间隔',
    'market.30s': '30秒',
    'market.1m': '1分钟',
    'market.5m': '5分钟',
    'market.15m': '15分钟',
    'market.lastUpdated': '最后更新',
    'market.gold': '黄金',
    'market.sp500': '标普500',
    'market.nasdaq': '纳斯达克',
    'market.us10y': '美国10年期国债',
    'market.usd': '美元指数',
    'market.oil': '原油',
    'market.price': '价格',
    'market.change': '涨跌',
    'market.changePercent': '涨跌幅',
    'market.correlation': '相关系数',
    'market.hedgeRatio': '对冲比例',
    'market.volatility': '波动率',
    'market.crisisMode': '危机模式',
    'market.crisisModeDesc': '当市场波动率超过阈值时自动高亮',
    'market.exportData': '导出数据',
    'market.exportCSV': '导出 CSV',
    'market.exportImage': '导出图片',
    'market.indicators': '指标图表',
    'market.correlationMatrix': '相关性矩阵',
    'market.hedgeEffectiveness': '对冲有效性',
    'market.settings': '设置',
    'market.alerts': '警报设置',
    'market.alertThreshold': '警报阈值',
    'market.enableAlerts': '启用警报',
    'market.silver': '白银',
    'market.djia': '道琼斯',
    'market.asset': '资产',
    'market.exportSuccess': '导出成功',
    'market.dataLoadError': '数据加载失败',
    'market.crisisModeAlert': '检测到高市场波动！',
    'market.priceChart': '价格图表',
    'market.hedgeAnalysis': '对冲分析',
    'market.rollingCorrelation': '滚动相关系数',
    'market.effectiveness': '有效性',
    'market.hedgeRecommendations': '对冲建议',
    'market.recommendedRatio': '建议比例',
    'market.rollingWindow': '滚动窗口',
    'market.periods': '期',
    'market.targetAsset': '目标资产',
    'market.refresh': '刷新',
    'market.volatilityLow': '低',
    'market.volatilityNormal': '中',
    'market.volatilityHigh': '高',
    'market.inflationLow': '低',
    'market.inflationHigh': '高',
    'market.panicHigh': '高恐慌',
    'market.regimeBull': '牛市',
    'market.regimeBear': '熊市',
    'market.regimeCrisis': '危机',
    'market.regimeRecovery': '复苏',
    'market.regimeUnknown': '未知',
    'market.assetDescription': '实时追踪该资产的价格、波动率和对冲表现',
    'market.priceChartDescription': '展示黄金、标普500和纳斯达克的24小时价格走势',
    'market.hedgeEffectivenessDescription': '比较不同资产的对冲效果和建议比例',
    'market.rollingCorrelationDescription': '展示黄金与目标资产的滚动相关系数变化',
    'market.correlationMatrixDescription': '热图展示各类资产之间的相关性矩阵',
    // 回测页面增强
    'backtest.asset': '资产类型',
    'backtest.timeWindow': '时间窗口',
    'backtest.export': '导出',
    'backtest.asset.stock': '大盘股票',
    'backtest.asset.tech': '科技行业',
    'backtest.asset.energy': '能源行业',
    'backtest.asset.finance': '金融行业',
    'backtest.asset.consumption': '消费行业',
    // 策略回测系统
    'strategy.title': '策略回测系统',
    'strategy.subtitle': '选择策略模板，点击开始回测查看结果',
    'strategy.editor': '策略编辑器',
    'strategy.selectTemplate': '选择策略模板',
    'strategy.simple': '简单均线策略',
    'strategy.simple.description': '最简单的策略，价格上穿均线买入，下穿卖出',
    'strategy.goldHedge': '黄金对冲策略',
    'strategy.goldHedge.description': '根据市场状态动态调整黄金配置',
    'strategy.tutorial': '使用说明',
    'strategy.step1': '选择策略',
    'strategy.step1.desc': '从下拉菜单选择一个策略模板，推荐先使用"简单均线策略"',
    'strategy.step2': '开始回测',
    'strategy.step2.desc': '点击右下角的"开始回测"按钮',
    'strategy.step3': '查看结果',
    'strategy.step3.desc': '查看收益率曲线、交易记录和各项指标',
    'strategy.step4': '尝试其他策略',
    'strategy.step4.desc': '切换到其他策略进行比较和研究',
    'strategy.description': '策略说明',
    'strategy.difficulty': '难度',
    'strategy.difficulty.easy': '简单',
    'strategy.difficulty.medium': '中等',
    'strategy.config': '配置参数',
    'strategy.initialCapital': '初始资金',
    'strategy.initialCapital.placeholder': '初始资金',
    'strategy.commission': '交易成本',
    'strategy.commission.placeholder': '交易成本',
    'strategy.slippage': '滑点',
    'strategy.slippage.placeholder': '滑点',
    'strategy.timePeriod': '回测周期',
    'strategy.timePeriod.placeholder': '选择回测周期',
    'strategy.timePeriod.1m': '1个月',
    'strategy.timePeriod.3m': '3个月',
    'strategy.timePeriod.6m': '6个月',
    'strategy.timePeriod.1y': '1年',
    'strategy.timePeriod.3y': '3年',
    'strategy.timePeriod.5y': '5年',
    'strategy.save': '保存策略',
    'strategy.export': '导出代码',
    'strategy.run': '开始回测',
    'strategy.running': '回测中...',
    'strategy.code': '策略代码',
    'strategy.apiHelp': 'API文档',
    // 回测结果
    'result.title': '回测结果',
    'result.totalReturn': '总收益率',
    'result.annualReturn': '年化收益',
    'result.maxDrawdown': '最大回撤',
    'result.sharpeRatio': '夏普比率',
    'result.winRate': '胜率',
    'result.totalTrades': '交易次数',
    'result.winningTrades': '盈利次数',
    'result.equityCurve': '资金曲线',
    'result.trades': '交易记录',
    'result.metrics': '详细指标',
    'result.benchmark': '基准收益',
    'result.volatility': '波动率',
    'result.profitFactor': '盈亏比',
    'result.buy': '买入',
    'result.sell': '卖出',
    'result.price': '价格',
    'result.amount': '数量',
    'result.asset': '资产',
    'result.reason': '原因',
    'result.date': '日期',
    'result.success': '回测完成！',
    'result.error': '回测失败',
    // AurumSignal Dashboard
    'aurum.title': 'AurumSignal Dashboard',
    'aurum.subtitle': '基于学术研究的黄金对冲策略工具',
    'aurum.dashboard': '仪表盘',
    'aurum.sectorSelector': '行业选择器',
    'aurum.riskConfigurator': '风险配置器',
    'aurum.deepAnalysis': '深度分析',
    'aurum.backtest': '回测',
    'aurum.strategyEngine': '策略引擎',
    'aurum.realTimeData': '实时市场数据',
    'aurum.inflation': '通胀率',
    'aurum.vix': 'VIX波动率指数',
    'aurum.dollarStrength': '美元指数',
    'aurum.goldPrice': '黄金价格',
    'aurum.conditionalBeta': '条件Beta',
    'aurum.hedgeEffectiveness': '对冲有效性',
    'aurum.channelContribution': '渠道贡献',
    'aurum.riskPreference': '风险偏好',
    'aurum.conservative': '保守',
    'aurum.moderate': '稳健',
    'aurum.aggressive': '激进',
    'aurum.recommendedAllocation': '建议配置',
    'aurum.scenarioAnalysis': '情景分析',
    'aurum.quantileRegression': '分位数回归',
    'aurum.asymmetricHedging': '非对称对冲',
    'aurum.crisisPerformance': '危机表现',
    'aurum.methodology': '方法论',
    'aurum.academicResearch': '学术研究',
    'aurum.hongKongTime': '香港时间',
    'aurum.sectors': {
      'energy': '能源',
      'utilities': '公用事业',
      'consumerStaples': '必需消费',
      'healthcare': '医疗健康',
      'financials': '金融',
      'industrials': '工业',
      'materials': '材料',
      'consumerDiscretionary': '可选消费',
      'technology': '科技',
      'communication': '通信',
      'realEstate': '房地产'
    }
  },
  'zh-TW': {
    // 导航
    'nav.assistant': '智能問答',
    'nav.risk': '風險評估',
    'nav.calculator': '行業配置',
    'nav.backtest': '回測看板',
    'nav.research': '研究結論',
    'nav.reports': '研究報告',
    'nav.contact': '聯繫作者',
    'nav.lang': '語言',

    // 风险评估
    'risk.title': '投資者風險評估',
    'risk.subtitle': '填寫問卷，獲得個性化的風險偏好分析和對沖建議',
    'risk.question.1.title': '投資經驗',
    'risk.question.1.desc': '您的投資經驗有多久？',
    'risk.question.1.option.1': '1年以內',
    'risk.question.1.option.2': '1-3年',
    'risk.question.1.option.3': '3-5年',
    'risk.question.1.option.4': '5年以上',
    'risk.question.2.title': '風險承受能力',
    'risk.question.2.desc': '當您的投資虧損20%時，您會怎麼做？',
    'risk.question.2.option.1': '立即全部止損',
    'risk.question.2.option.2': '部分止損，等待機會',
    'risk.question.2.option.3': '保持持有，等待反彈',
    'risk.question.2.option.4': '逆勢加倉',
    'risk.question.3.title': '投資目標',
    'risk.question.3.desc': '您的主要投資目標是什麼？',
    'risk.question.3.option.1': '保本為主，少量增值',
    'risk.question.3.option.2': '穩健增值，適度波動',
    'risk.question.3.option.3': '追求較高收益，接受波動',
    'risk.question.3.option.4': '最大化收益，願承擔高風險',
    'risk.question.4.title': '投資期限',
    'risk.question.4.desc': '您的投資期限是多久？',
    'risk.question.4.option.1': '1年以內',
    'risk.question.4.option.2': '1-3年',
    'risk.question.4.option.3': '3-5年',
    'risk.question.4.option.4': '5年以上',
    'risk.next': '下一題',
    'risk.prev': '上一題',
    'risk.submit': '查看結果',
    'risk.result.title': '您的風險評估結果',
    'risk.result.profile': '風險偏好類型',
    'risk.result.recommendation': '對沖配置建議',
    'risk.result.gold.ratio': '建議黃金配置比例',
    'risk.result.description': '詳細說明',
    'risk.type.conservative': '保守型投資者',
    'risk.type.moderate': '穩健型投資者',
    'risk.type.balanced': '平衡型投資者',
    'risk.type.aggressive': '進取型投資者',
    'risk.type.veryAggressive': '激進型投資者',
    'risk.retake': '重新評估',
    'risk.goToCalculator': '使用計算器細化',

    // 首頁 - 智能問答
    'home.hero.title': '黃金 · 股票跨資產自適應對沖策略',
    'home.hero.subtitle': '用智能問答，秒級獲取您專屬的黃金ETF配置方案',
    'home.placeholder': '例如：我重倉了科技股，應該配多少黃金對沖？',
    'home.submit': '生成建議',
    'home.examples.title': '試試這些問題',
    'home.examples.1': '我重倉了科技股，應該配多少黃金對沖？',
    'home.examples.2': '現在通脹高，能源股配多少黃金合適？',
    'home.examples.3': '保守型投資者，消費行業怎麼配黃金ETF？',
    'home.result.title': '配置建議',
    'home.result.ratio': '建議黃金配置比例',
    'home.result.logic': '對沖邏輯說明',
    'home.result.risk': '風險提示',
    'home.result.loading': '正在為您分析...',
    'home.result.analyzing': '正在解析您的問題...',
    'home.result.generating': '正在生成配置建議...',
    'home.result.error': '解析失敗，請嘗試更明確的描述，或使用行業配置計算器手動調整。',
    'home.model.select': '選擇AI模型',
    'home.ai.settings': 'AI設置',

    // 計算器
    'calc.title': '行業配置計算器',
    'calc.subtitle': '選擇行業與市場參數，實時計算最優黃金對沖比例',
    'calc.industry': '選擇行業',
    'calc.risk': '風險偏好',
    'calc.risk.conservative': '保守型',
    'calc.risk.moderate': '穩健型',
    'calc.risk.aggressive': '激進型',
    'calc.market': '市場狀態調節',
    'calc.volatility': '市場波動',
    'calc.volatility.low': '低波動',
    'calc.volatility.normal': '正常',
    'calc.volatility.high': '高波動',
    'calc.inflation': '通脹水平',
    'calc.inflation.low': '低通脹',
    'calc.inflation.high': '高通脹',
    'calc.panic': '恐慌程度',
    'calc.panic.low': '低恐慌',
    'calc.panic.high': '高恐慌',
    'calc.result.title': '計算結果',
    'calc.result.ratio': '建議黃金ETF配置比例',
    'calc.result.effect': '預期對沖效果',
    'calc.result.protection': '下行保護強度',
    'calc.formula.title': '計算過程',
    'calc.formula.base': '基準比例',
    'calc.formula.industry': '行業係數',
    'calc.formula.market': '市場調整',
    'calc.formula.result': '最終比例',
    'calc.effect.strong': '強',
    'calc.effect.medium': '中',
    'calc.effect.weak': '弱',

    // 回測
    'backtest.title': '策略回測看板',
    'backtest.subtitle': '自適應策略 vs 靜態對沖 vs 純股票，歷史表現一目了然',
    'backtest.kpi.annual': '年化收益',
    'backtest.kpi.drawdown': '最大回撤',
    'backtest.kpi.sharpe': '夏普比率',
    'backtest.kpi.protection': '下行保護率',
    'backtest.chart.curve': '累計收益對比',
    'backtest.chart.inflation': '通脹狀態分佈',
    'backtest.chart.vix': 'VIX狀態分佈',
    'backtest.strategy.adaptive': '自適應策略',
    'backtest.strategy.static': '靜態對沖',
    'backtest.strategy.stock': '純股票',
    'backtest.inflation.high': '高通脹',
    'backtest.inflation.low': '低通脹',
    'backtest.vix.high': '高VIX',
    'backtest.vix.low': '低VIX',

    // 研究結論
    'research.title': '核心研究發現',
    'research.subtitle': '基於十年跨資產數據的實證結論',
    'research.f1.title': '行業異質性',
    'research.f1.desc': '不同行業對黃金對沖的敏感度差異顯著，能源、公用事業等週期防禦型行業對沖效果最強，科技、地產等成長/利率敏感型行業相對較弱。',
    'research.f2.title': '狀態依賴',
    'research.f2.desc': '黃金對沖效果高度依賴市場狀態：高通脹、高恐慌、高波動環境下對沖效率顯著提升，平穩市場中則表現為收益拖累。',
    'research.f3.title': '非對稱對沖',
    'research.f3.desc': '黃金在股市下跌時的保護作用遠強於上漲時的拖累效應，呈現典型的"危機Alpha"非對稱特徵，下行保護率顯著高於上行損耗率。',
    'research.f4.title': '避險邊界',
    'research.f4.desc': '黃金對沖並非萬能：在美元流動性危機、實際利率快速上行等特殊場景下，黃金與股票可能同步下跌，需警惕避險資產的階段性失效風險。',

    // 聯繫作者
    'contact.title': '聯繫作者',
    'contact.subtitle': '如有任何問題或合作意向，請聯繫我們',
    'contact.email': '郵箱',
    'contact.email.placeholder': '請輸入您的郵箱',
    'contact.message': '消息',
    'contact.message.placeholder': '請輸入您的消息',
    'contact.submit': '發送',
    'contact.success': '消息發送成功！',
    'contact.or.write': '或直接發送郵件至',
    'contact.info': '關於本項目',
    'contact.info.desc': '本項目旨在幫助投資者科學地進行黃金與股票的跨資產對沖配置，基於學術研究成果開發。',

    // 通用
    'common.percent': '%',
    'common.vs': '對比',
    'common.basisPoint': 'bp',
    // 市场看板
    'nav.market': '市場看板',
    'market.title': '實時市場數據看板',
    'market.subtitle': '實時追蹤黃金、股票和外匯等資產的對沖表現',
    'market.updateMode': '更新模式',
    'market.polling': '輪詢模式',
    'market.websocket': 'WebSocket 實時',
    'market.refreshInterval': '刷新間隔',
    'market.30s': '30秒',
    'market.1m': '1分鐘',
    'market.5m': '5分鐘',
    'market.15m': '15分鐘',
    'market.lastUpdated': '最後更新',
    'market.gold': '黃金',
    'market.sp500': '標普500',
    'market.nasdaq': '納斯達克',
    'market.us10y': '美國10年期國債',
    'market.usd': '美元指數',
    'market.oil': '原油',
    'market.price': '價格',
    'market.change': '漲跌',
    'market.changePercent': '漲跌幅',
    'market.correlation': '相關係數',
    'market.hedgeRatio': '對沖比例',
    'market.volatility': '波動率',
    'market.crisisMode': '危機模式',
    'market.crisisModeDesc': '當市場波動率超過閾值時自動高亮',
    'market.exportData': '導出數據',
    'market.exportCSV': '導出 CSV',
    'market.exportImage': '導出圖片',
    'market.indicators': '指標圖表',
    'market.correlationMatrix': '相關性矩陣',
    'market.hedgeEffectiveness': '對沖有效性',
    'market.settings': '設置',
    'market.alerts': '警報設置',
    'market.alertThreshold': '警報閾值',
    'market.enableAlerts': '啟用警報',
    'market.silver': '白銀',
    'market.djia': '道瓊斯',
    'market.asset': '資產',
    'market.exportSuccess': '導出成功',
    'market.dataLoadError': '數據加載失敗',
    'market.crisisModeAlert': '檢測到高市場波動！',
    'market.priceChart': '價格圖表',
    'market.hedgeAnalysis': '對沖分析',
    'market.rollingCorrelation': '滾動相關係數',
    'market.effectiveness': '有效性',
    'market.hedgeRecommendations': '對沖建議',
    'market.recommendedRatio': '建議比例',
    'market.rollingWindow': '滾動窗口',
    'market.periods': '期',
    'market.targetAsset': '目標資產',
    'market.refresh': '刷新',
    'market.volatilityLow': '低',
    'market.volatilityNormal': '中',
    'market.volatilityHigh': '高',
    'market.inflationLow': '低',
    'market.inflationHigh': '高',
    'market.panicHigh': '高恐慌',
    'market.regimeBull': '牛市',
    'market.regimeBear': '熊市',
    'market.regimeCrisis': '危機',
    'market.regimeRecovery': '復甦',
    'market.regimeUnknown': '未知',
    'market.assetDescription': '實時追蹤該資產的價格、波動率和對沖表現',
    'market.priceChartDescription': '展示黃金、標普500和納斯達克的24小時價格走勢',
    'market.hedgeEffectivenessDescription': '比較不同資產的對沖效果和建議比例',
    'market.rollingCorrelationDescription': '展示黃金與目標資產的滾動相關係數變化',
    'market.correlationMatrixDescription': '熱圖展示各類資產之間的相關性矩陣',
    // 回测页面增强
    'backtest.asset': '資產類型',
    'backtest.timeWindow': '時間窗口',
    'backtest.export': '導出',
    'backtest.asset.stock': '大盤股票',
    'backtest.asset.tech': '科技行業',
    'backtest.asset.energy': '能源行業',
    'backtest.asset.finance': '金融行業',
    'backtest.asset.consumption': '消費行業',
    // 策略回測系統
    'strategy.title': '策略回測系統',
    'strategy.subtitle': '選擇策略模板，點擊開始回測查看結果',
    'strategy.editor': '策略編輯器',
    'strategy.selectTemplate': '選擇策略模板',
    'strategy.simple': '簡單均線策略',
    'strategy.simple.description': '最簡單的策略，價格上穿均線買入，下穿賣出',
    'strategy.goldHedge': '黃金對沖策略',
    'strategy.goldHedge.description': '根據市場狀態動態調整黃金配置',
    'strategy.tutorial': '使用說明',
    'strategy.step1': '選擇策略',
    'strategy.step1.desc': '從下拉菜單選擇一個策略模板，推薦先使用"簡單均線策略"',
    'strategy.step2': '開始回測',
    'strategy.step2.desc': '點擊右下角的"開始回測"按鈕',
    'strategy.step3': '查看結果',
    'strategy.step3.desc': '查看收益率曲線、交易記錄和各項指標',
    'strategy.step4': '嘗試其他策略',
    'strategy.step4.desc': '切換到其他策略進行比較和研究',
    'strategy.description': '策略說明',
    'strategy.difficulty': '難度',
    'strategy.difficulty.easy': '簡單',
    'strategy.difficulty.medium': '中等',
    'strategy.config': '配置參數',
    'strategy.initialCapital': '初始資金',
    'strategy.initialCapital.placeholder': '初始資金',
    'strategy.commission': '交易成本',
    'strategy.commission.placeholder': '交易成本',
    'strategy.slippage': '滑點',
    'strategy.slippage.placeholder': '滑點',
    'strategy.timePeriod': '回測週期',
    'strategy.timePeriod.placeholder': '選擇回測週期',
    'strategy.timePeriod.1m': '1個月',
    'strategy.timePeriod.3m': '3個月',
    'strategy.timePeriod.6m': '6個月',
    'strategy.timePeriod.1y': '1年',
    'strategy.timePeriod.3y': '3年',
    'strategy.timePeriod.5y': '5年',
    'strategy.save': '保存策略',
    'strategy.export': '導出代碼',
    'strategy.run': '開始回測',
    'strategy.running': '回測中...',
    'strategy.code': '策略代碼',
    'strategy.apiHelp': 'API文檔',
    // 回測結果
    'result.title': '回測結果',
    'result.totalReturn': '總收益率',
    'result.annualReturn': '年化收益',
    'result.maxDrawdown': '最大回撤',
    'result.sharpeRatio': '夏普比率',
    'result.winRate': '勝率',
    'result.totalTrades': '交易次數',
    'result.winningTrades': '盈利次數',
    'result.equityCurve': '資金曲線',
    'result.trades': '交易記錄',
    'result.metrics': '詳細指標',
    'result.benchmark': '基準收益',
    'result.volatility': '波動率',
    'result.profitFactor': '盈虧比',
    'result.buy': '買入',
    'result.sell': '賣出',
    'result.price': '價格',
    'result.amount': '數量',
    'result.asset': '資產',
    'result.reason': '原因',
    'result.date': '日期',
    'result.success': '回測完成！',
    'result.error': '回測失敗',
  },
  en: {
    // Nav
    'nav.assistant': 'AI Assistant',
    'nav.risk': 'Risk Assessment',
    'nav.calculator': 'Calculator',
    'nav.backtest': 'Backtest',
    'nav.research': 'Research',
    'nav.reports': 'Research Reports',
    'nav.contact': 'Contact',
    'nav.lang': 'Language',

    // Risk Assessment
    'risk.title': 'Investor Risk Assessment',
    'risk.subtitle': 'Fill out the questionnaire for personalized risk profile analysis and hedging recommendations',
    'risk.question.1.title': 'Investment Experience',
    'risk.question.1.desc': 'How long have you been investing?',
    'risk.question.1.option.1': 'Less than 1 year',
    'risk.question.1.option.2': '1-3 years',
    'risk.question.1.option.3': '3-5 years',
    'risk.question.1.option.4': 'More than 5 years',
    'risk.question.2.title': 'Risk Tolerance',
    'risk.question.2.desc': 'What would you do if your investment lost 20%?',
    'risk.question.2.option.1': 'Sell all immediately',
    'risk.question.2.option.2': 'Sell partially and wait',
    'risk.question.2.option.3': 'Hold and wait for recovery',
    'risk.question.2.option.4': 'Buy more on the dip',
    'risk.question.3.title': 'Investment Goal',
    'risk.question.3.desc': 'What is your main investment goal?',
    'risk.question.3.option.1': 'Capital preservation, minimal growth',
    'risk.question.3.option.2': 'Stable growth, moderate volatility',
    'risk.question.3.option.3': 'Higher returns, accept volatility',
    'risk.question.3.option.4': 'Maximize returns, accept high risk',
    'risk.question.4.title': 'Investment Horizon',
    'risk.question.4.desc': 'How long is your investment horizon?',
    'risk.question.4.option.1': 'Less than 1 year',
    'risk.question.4.option.2': '1-3 years',
    'risk.question.4.option.3': '3-5 years',
    'risk.question.4.option.4': 'More than 5 years',
    'risk.next': 'Next',
    'risk.prev': 'Previous',
    'risk.submit': 'View Results',
    'risk.result.title': 'Your Risk Assessment Results',
    'risk.result.profile': 'Risk Profile',
    'risk.result.recommendation': 'Hedging Recommendation',
    'risk.result.gold.ratio': 'Suggested Gold Allocation',
    'risk.result.description': 'Detailed Description',
    'risk.type.conservative': 'Conservative Investor',
    'risk.type.moderate': 'Moderate Investor',
    'risk.type.balanced': 'Balanced Investor',
    'risk.type.aggressive': 'Growth Investor',
    'risk.type.veryAggressive': 'Aggressive Investor',
    'risk.retake': 'Retake Assessment',
    'risk.goToCalculator': 'Use Calculator to Refine',

    // Home
    'home.hero.title': 'Gold · Stock Cross-Asset Adaptive Hedging',
    'home.hero.subtitle': 'Get your personalized gold ETF allocation in seconds with AI',
    'home.placeholder': 'e.g. I hold heavy tech stocks, how much gold should I allocate?',
    'home.submit': 'Generate Advice',
    'home.examples.title': 'Try these questions',
    'home.examples.1': 'I hold heavy tech stocks, how much gold should I allocate for hedging?',
    'home.examples.2': 'Inflation is high now, how much gold for energy stocks?',
    'home.examples.3': 'Conservative investor, how to allocate gold ETF for consumer sector?',
    'home.result.title': 'Allocation Advice',
    'home.result.ratio': 'Suggested Gold Allocation',
    'home.result.logic': 'Hedging Rationale',
    'home.result.risk': 'Risk Warnings',
    'home.result.loading': 'Analyzing your question...',
    'home.result.analyzing': 'Parsing your query...',
    'home.result.generating': 'Generating allocation advice...',
    'home.result.error': 'Failed to parse. Please try a more specific description, or use the calculator to adjust manually.',
    'home.model.select': 'Select AI Model',
    'home.ai.settings': 'AI Settings',

    // Calculator
    'calc.title': 'Industry Allocation Calculator',
    'calc.subtitle': 'Select industry and market parameters to calculate optimal gold hedge ratio in real time',
    'calc.industry': 'Select Industry',
    'calc.risk': 'Risk Preference',
    'calc.risk.conservative': 'Conservative',
    'calc.risk.moderate': 'Moderate',
    'calc.risk.aggressive': 'Aggressive',
    'calc.market': 'Market Condition Adjustment',
    'calc.volatility': 'Market Volatility',
    'calc.volatility.low': 'Low',
    'calc.volatility.normal': 'Normal',
    'calc.volatility.high': 'High',
    'calc.inflation': 'Inflation Level',
    'calc.inflation.low': 'Low Inflation',
    'calc.inflation.high': 'High Inflation',
    'calc.panic': 'Panic Level',
    'calc.panic.low': 'Low Panic',
    'calc.panic.high': 'High Panic',
    'calc.result.title': 'Calculation Result',
    'calc.result.ratio': 'Suggested Gold ETF Allocation',
    'calc.result.effect': 'Expected Hedge Effect',
    'calc.result.protection': 'Downside Protection',
    'calc.formula.title': 'Calculation Breakdown',
    'calc.formula.base': 'Base Ratio',
    'calc.formula.industry': 'Industry Factor',
    'calc.formula.market': 'Market Adjustment',
    'calc.formula.result': 'Final Ratio',
    'calc.effect.strong': 'Strong',
    'calc.effect.medium': 'Medium',
    'calc.effect.weak': 'Weak',

    // Backtest
    'backtest.title': 'Strategy Backtest Dashboard',
    'backtest.subtitle': 'Adaptive vs Static Hedge vs Pure Stocks — historical performance at a glance',
    'backtest.kpi.annual': 'Annual Return',
    'backtest.kpi.drawdown': 'Max Drawdown',
    'backtest.kpi.sharpe': 'Sharpe Ratio',
    'backtest.kpi.protection': 'Downside Protection',
    'backtest.chart.curve': 'Cumulative Return Comparison',
    'backtest.chart.inflation': 'Inflation Regime Distribution',
    'backtest.chart.vix': 'VIX Regime Distribution',
    'backtest.strategy.adaptive': 'Adaptive Strategy',
    'backtest.strategy.static': 'Static Hedge',
    'backtest.strategy.stock': 'Pure Stocks',
    'backtest.inflation.high': 'High Inflation',
    'backtest.inflation.low': 'Low Inflation',
    'backtest.vix.high': 'High VIX',
    'backtest.vix.low': 'Low VIX',

    // Research
    'research.title': 'Key Research Findings',
    'research.subtitle': 'Empirical conclusions based on ten years of cross-asset data',
    'research.f1.title': 'Industry Heterogeneity',
    'research.f1.desc': 'Sensitivity to gold hedging varies significantly across industries. Cyclical/defensive sectors like energy and utilities show the strongest hedge effect, while growth/rate-sensitive sectors like tech and real estate are relatively weaker.',
    'research.f2.title': 'State Dependence',
    'research.f2.desc': 'Gold hedging effectiveness is highly state-dependent: hedge efficiency improves significantly in high-inflation, high-panic, and high-volatility environments, but acts as a return drag in calm markets.',
    'research.f3.title': 'Asymmetric Hedging',
    'research.f3.desc': "Gold's protection during stock market declines far outweighs its drag during rallies — a classic 'crisis alpha' asymmetric pattern, with downside protection significantly exceeding upside loss.",
    'research.f4.title': 'Safe-Haven Boundary',
    'research.f4.desc': "Gold hedging is not omnipotent: in special scenarios like dollar liquidity crises or rapid real-rate spikes, gold and stocks may fall together. Watch for periodic failure of safe-haven assets.",

    // Contact
    'contact.title': 'Contact Author',
    'contact.subtitle': 'Have any questions or collaboration ideas? Get in touch with us',
    'contact.email': 'Email',
    'contact.email.placeholder': 'Enter your email',
    'contact.message': 'Message',
    'contact.message.placeholder': 'Enter your message',
    'contact.submit': 'Send',
    'contact.success': 'Message sent successfully!',
    'contact.or.write': 'Or email us directly at',
    'contact.info': 'About This Project',
    'contact.info.desc': 'This project helps investors scientifically allocate gold and stock cross-asset hedging, developed based on academic research.',

    // Common
    'common.percent': '%',
    'common.vs': 'vs',
    'common.basisPoint': 'bp',
    // Market Dashboard
    'nav.market': 'Market Dashboard',
    'market.title': 'Real-Time Market Dashboard',
    'market.subtitle': 'Track gold, stock, and forex hedging performance in real-time',
    'market.updateMode': 'Update Mode',
    'market.polling': 'Polling',
    'market.websocket': 'WebSocket Live',
    'market.refreshInterval': 'Refresh Interval',
    'market.30s': '30s',
    'market.1m': '1min',
    'market.5m': '5min',
    'market.15m': '15min',
    'market.lastUpdated': 'Last Updated',
    'market.gold': 'Gold',
    'market.sp500': 'S&P 500',
    'market.nasdaq': 'NASDAQ',
    'market.us10y': 'US 10Y Treasury',
    'market.usd': 'US Dollar Index',
    'market.oil': 'Crude Oil',
    'market.price': 'Price',
    'market.change': 'Change',
    'market.changePercent': 'Change %',
    'market.correlation': 'Correlation',
    'market.hedgeRatio': 'Hedge Ratio',
    'market.volatility': 'Volatility',
    'market.crisisMode': 'Crisis Mode',
    'market.crisisModeDesc': 'Auto-highlight when volatility exceeds threshold',
    'market.exportData': 'Export Data',
    'market.exportCSV': 'Export CSV',
    'market.exportImage': 'Export Image',
    'market.indicators': 'Indicators',
    'market.correlationMatrix': 'Correlation Matrix',
    'market.hedgeEffectiveness': 'Hedge Effectiveness',
    'market.settings': 'Settings',
    'market.alerts': 'Alert Settings',
    'market.alertThreshold': 'Alert Threshold',
    'market.enableAlerts': 'Enable Alerts',
    'market.silver': 'Silver',
    'market.djia': 'Dow Jones',
    'market.asset': 'Asset',
    'market.exportSuccess': 'Export successful',
    'market.dataLoadError': 'Failed to load data',
    'market.crisisModeAlert': 'High market volatility detected!',
    'market.priceChart': 'Price Chart',
    'market.hedgeAnalysis': 'Hedge Analysis',
    'market.rollingCorrelation': 'Rolling Correlation',
    'market.effectiveness': 'Effectiveness',
    'market.hedgeRecommendations': 'Hedge Recommendations',
    'market.recommendedRatio': 'Recommended Ratio',
    'market.rollingWindow': 'Rolling Window',
    'market.periods': 'periods',
    'market.targetAsset': 'Target Asset',
    'market.refresh': 'Refresh',
    'market.volatilityLow': 'Low',
    'market.volatilityNormal': 'Normal',
    'market.volatilityHigh': 'High',
    'market.inflationLow': 'Low',
    'market.inflationHigh': 'High',
    'market.panicHigh': 'High Panic',
    'market.regimeBull': 'Bull',
    'market.regimeBear': 'Bear',
    'market.regimeCrisis': 'Crisis',
    'market.regimeRecovery': 'Recovery',
    'market.regimeUnknown': 'Unknown',
    'market.assetDescription': 'Real-time tracking of price, volatility, and hedge performance',
    'market.priceChartDescription': '24-hour price trends for gold, S&P 500, and NASDAQ',
    'market.hedgeEffectivenessDescription': 'Compare hedge effectiveness and recommended ratios for different assets',
    'market.rollingCorrelationDescription': 'Shows rolling correlation changes between gold and target asset',
    'market.correlationMatrixDescription': 'Heatmap showing correlation matrix between all assets',
    // Backtest enhancements
    'backtest.asset': 'Asset Type',
    'backtest.timeWindow': 'Time Window',
    'backtest.export': 'Export',
    'backtest.asset.stock': 'Broad Market',
    'backtest.asset.tech': 'Technology',
    'backtest.asset.energy': 'Energy',
    'backtest.asset.finance': 'Finance',
    'backtest.asset.consumption': 'Consumption',
    // Strategy Backtest System
    'strategy.title': 'Strategy Backtest System',
    'strategy.subtitle': 'Select a strategy template and click Run Backtest to view results',
    'strategy.editor': 'Strategy Editor',
    'strategy.selectTemplate': 'Select Strategy Template',
    'strategy.simple': 'Simple Moving Average',
    'strategy.simple.description': 'The simplest strategy: buy when price crosses above MA, sell when it crosses below',
    'strategy.goldHedge': 'Gold Hedging Strategy',
    'strategy.goldHedge.description': 'Dynamically adjust gold allocation based on market conditions',
    'strategy.tutorial': 'How to Use',
    'strategy.step1': 'Select Strategy',
    'strategy.step1.desc': 'Choose a strategy template from the dropdown menu. We recommend starting with "Simple Moving Average"',
    'strategy.step2': 'Run Backtest',
    'strategy.step2.desc': 'Click the "Run Backtest" button in the bottom right',
    'strategy.step3': 'View Results',
    'strategy.step3.desc': 'View the equity curve, trade history, and performance metrics',
    'strategy.step4': 'Try Other Strategies',
    'strategy.step4.desc': 'Switch to other strategies for comparison and research',
    'strategy.description': 'Strategy Description',
    'strategy.difficulty': 'Difficulty',
    'strategy.difficulty.easy': 'Easy',
    'strategy.difficulty.medium': 'Medium',
    'strategy.config': 'Configuration',
    'strategy.initialCapital': 'Initial Capital',
    'strategy.initialCapital.placeholder': 'Initial Capital',
    'strategy.commission': 'Commission Rate',
    'strategy.commission.placeholder': 'Commission Rate',
    'strategy.slippage': 'Slippage',
    'strategy.slippage.placeholder': 'Slippage',
    'strategy.timePeriod': 'Backtest Period',
    'strategy.timePeriod.placeholder': 'Select Backtest Period',
    'strategy.timePeriod.1m': '1 Month',
    'strategy.timePeriod.3m': '3 Months',
    'strategy.timePeriod.6m': '6 Months',
    'strategy.timePeriod.1y': '1 Year',
    'strategy.timePeriod.3y': '3 Years',
    'strategy.timePeriod.5y': '5 Years',
    'strategy.save': 'Save Strategy',
    'strategy.export': 'Export Code',
    'strategy.run': 'Run Backtest',
    'strategy.running': 'Running...',
    'strategy.code': 'Strategy Code',
    'strategy.apiHelp': 'API Reference',
    // Backtest Results
    'result.title': 'Backtest Results',
    'result.totalReturn': 'Total Return',
    'result.annualReturn': 'Annual Return',
    'result.maxDrawdown': 'Max Drawdown',
    'result.sharpeRatio': 'Sharpe Ratio',
    'result.winRate': 'Win Rate',
    'result.totalTrades': 'Total Trades',
    'result.winningTrades': 'Winning Trades',
    'result.equityCurve': 'Equity Curve',
    'result.trades': 'Trade History',
    'result.metrics': 'Detailed Metrics',
    'result.benchmark': 'Benchmark Return',
    'result.volatility': 'Volatility',
    'result.profitFactor': 'Profit Factor',
    'result.buy': 'Buy',
    'result.sell': 'Sell',
    'result.price': 'Price',
    'result.amount': 'Amount',
    'result.asset': 'Asset',
    'result.reason': 'Reason',
    'result.date': 'Date',
    'result.success': 'Backtest complete!',
    'result.error': 'Backtest failed',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('zh-CN');

  useEffect(() => {
    const saved = localStorage.getItem(STORAGE_KEY) as Lang | null;
    if (saved && (saved === 'zh-CN' || saved === 'zh-TW' || saved === 'en')) {
      setLangState(saved);
    }
  }, []);

  const setLang = useCallback((newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem(STORAGE_KEY, newLang);
  }, []);

  const toggleLang = useCallback(() => {
    // 循环切换：zh-CN -> zh-TW -> en -> zh-CN
    if (lang === 'zh-CN') setLangState('zh-TW');
    else if (lang === 'zh-TW') setLangState('en');
    else setLangState('zh-CN');
  }, [lang, setLangState]);

  const t = useCallback(
    (key: string) => translations[lang][key] ?? key,
    [lang],
  );

  const value = useMemo(
    () => ({ lang, setLang, toggleLang, t }),
    [lang, setLang, toggleLang, t],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
